// ai-tools-advanced-integrations/frontend-integration/angular/src/app/components/confirmation-dialog/confirmation-dialog.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  HostListener,
} from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Confirmation Dialog Component
 * Custom dialog to replace native browser confirm()
 */
@Component({
  selector: 'app-confirmation-dialog',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './confirmation-dialog.html',
  styleUrl: './confirmation-dialog.css',
})
export class ConfirmationDialogComponent {
  @Input() visible: boolean = false;
  @Input() title: string = 'Confirm';
  @Input() message: string = 'Are you sure?';
  @Input() confirmText: string = 'Confirm';
  @Input() cancelText: string = 'Cancel';
  @Input() showCheckbox: boolean = false;
  @Input() checkboxLabel: string = '';
  @Input() checkboxChecked: boolean = false;
  @Output() confirm = new EventEmitter<void>();
  @Output() cancel = new EventEmitter<void>();
  @Output() close = new EventEmitter<void>();
  @Output() checkboxChange = new EventEmitter<boolean>();

  onCheckboxChange(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.checkboxChange.emit(checked);
  }

  @HostListener('document:keydown.escape', ['$event'])
  handleEscape(event: KeyboardEvent): void {
    if (this.visible) {
      this.handleCancel();
    }
  }

  @HostListener('document:keydown.enter', ['$event'])
  handleEnter(event: KeyboardEvent): void {
    if (this.visible && !event.defaultPrevented) {
      // Only confirm if focus is not on an input/textarea
      const target = event.target as HTMLElement;
      if (target.tagName !== 'INPUT' && target.tagName !== 'TEXTAREA') {
        this.handleConfirm();
      }
    }
  }

  handleConfirm(): void {
    this.confirm.emit();
    this.close.emit();
  }

  handleCancel(): void {
    this.cancel.emit();
    this.close.emit();
  }

  handleBackdropClick(event: MouseEvent): void {
    // Only close if clicking directly on the backdrop
    if ((event.target as HTMLElement).classList.contains('dialog-backdrop')) {
      this.handleCancel();
    }
  }
}

// ai-tools-advanced-integrations/frontend-integration/react/src/components/ConfirmationDialog.tsx
import { useEffect, useCallback } from 'react';
import './ConfirmationDialog.css';

interface ConfirmationDialogProps {
  visible: boolean;
  title?: string;
  message?: string;
  confirmText?: string;
  cancelText?: string;
  showCheckbox?: boolean;
  checkboxLabel?: string;
  checkboxChecked?: boolean;
  onCheckboxChange?: (checked: boolean) => void;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmationDialog({
  visible,
  title = 'Confirm',
  message = 'Are you sure?',
  confirmText = 'Confirm',
  cancelText = 'Cancel',
  showCheckbox = false,
  checkboxLabel = '',
  checkboxChecked = false,
  onCheckboxChange,
  onConfirm,
  onCancel,
}: ConfirmationDialogProps) {
  const handleKeyDown = useCallback(
    (event: KeyboardEvent) => {
      if (!visible) return;

      if (event.key === 'Escape') {
        onCancel();
      } else if (event.key === 'Enter') {
        const target = event.target as HTMLElement;
        if (target.tagName !== 'INPUT' && target.tagName !== 'TEXTAREA') {
          onConfirm();
        }
      }
    },
    [visible, onConfirm, onCancel]
  );

  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  if (!visible) return null;

  const handleBackdropClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if ((event.target as HTMLElement).classList.contains('dialog-backdrop')) {
      onCancel();
    }
  };

  return (
    <div className="dialog-backdrop" onClick={handleBackdropClick}>
      <div
        className="dialog-container"
        role="dialog"
        aria-modal="true"
        aria-labelledby="dialog-title"
        aria-describedby="dialog-message"
      >
        <div className="dialog-header">
          <h3 id="dialog-title" className="dialog-title">
            {title}
          </h3>
        </div>

        <div className="dialog-body">
          <p id="dialog-message" className="dialog-message">
            {message}
          </p>
        </div>

        {showCheckbox && (
          <div className="dialog-checkbox">
            <label>
              <input
                type="checkbox"
                checked={checkboxChecked}
                onChange={(e) => onCheckboxChange?.(e.target.checked)}
              />
              {checkboxLabel}
            </label>
          </div>
        )}

        <div className="dialog-actions">
          <button
            type="button"
            className="dialog-button dialog-button-cancel"
            onClick={onCancel}
            aria-label={cancelText}
          >
            {cancelText}
          </button>
          <button
            type="button"
            className="dialog-button dialog-button-confirm"
            onClick={onConfirm}
            aria-label={confirmText}
          >
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
}
